version: "3"

networks:
  public:
    driver: bridge
    enable_ipv6: true
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 10.40.99.0/24
        - subnet: fd40:99::/64
  signaling-backend:
    driver: bridge
    enable_ipv6: true
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.40.102.0/24
        - subnet: fd40:102::/64
  proxy-net:
    external:
      name: ${PROXY_NETWORK}


services:
  ### Middleware ###
  signaling:
    build: signaling/build
    read_only: true
    restart: always
    depends_on:
      - janus
      - nats
      - coturn
    environment:
      - TZ=${TZ}
      - TURN_API_KEY=${TURN_API_KEY}
      - HASH_KEY=${HASH_KEY}
      - BLOCK_KEY=${BLOCK_KEY}
      - JANUS_API_KEY=${JANUS_API_KEY}
    volumes:
      - ./signaling/server.conf:/etc/signaling/server.conf.template:ro,Z
      - ./signaling/nextcloud.conf:/etc/signaling/nextcloud.conf.template:ro,Z
    tmpfs:
      - /config:uid=1500,gid=0
    cap_drop:
     - ALL
    networks:
      public:
        aliases:
          - signaling
      proxy-net:
        aliases:
          - signaling
      signaling-backend:
        aliases:
          - signaling

  ### Backend ###
  janus:
    build: janus/build
    read_only: true
    restart: always
    depends_on:
      - coturn
    environment:
      - TZ=${TZ}
      - TURN_API_KEY=${TURN_API_KEY}
      - JANUS_API_KEY=${JANUS_API_KEY}
      - SIGNALING_HOSTNAME=${SIGNALING_HOSTNAME}
    volumes:
      - ./janus/janus.jcfg:/etc/janus/janus.jcfg.template:ro,Z
      - ./janus/janus.transport.http.jcfg:/etc/janus/janus.transport.http.jcfg:ro,Z
      - ./janus/janus.transport.mqtt.jcfg:/etc/janus/janus.transport.mqtt.jcfg:ro,Z
      - ./janus/janus.transport.websockets.jcfg:/etc/janus/janus.transport.websockets.jcfg:ro,Z
      - ./janus/janus.transport.nanomsg.jcfg:/etc/janus/janus.transport.nanomsg.jcfg:ro,Z
    tmpfs:
      - /janustmp/:uid=1500,gid=0
      - /usr/share/janus/demos:uid=1500,gid=0
      - /usr/share/janus/streams:uid=1500,gid=0
      - /usr/share/janus/recordings:uid=1500,gid=0
    ports:
      - "20000-20100:20000-20100/udp"
    cap_drop:
     - ALL
    networks:
      public:
        aliases:
          - janus

  coturn:
    build: coturn/build
    read_only: true
    restart: always
    environment:
      - TZ=${TZ}
      - SIGNALING_HOSTNAME=${SIGNALING_HOSTNAME}
      - TURN_API_KEY=${TURN_API_KEY}
    volumes:
      - ./coturn/turnserver.conf:/etc/turnserver.conf.template:ro,Z
    tmpfs:
      - /turntmp:uid=100,gid=0
      - /var/lib/coturn/:uid=100,gid=0
      - /run:uid=100,gid=0
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "49160-49200:49160-49200/udp"
    cap_drop:
      - ALL
    networks:
      public:
        aliases:
          - coturn
      
  nats:
    #image: nats:alpine
    build: nats/build
    read_only: true
    command: ["-c", "/config/gnatsd.conf"]
    restart: always
    environment:
      - TZ=${TZ}
    volumes:
      - ./nats/gnatsd.conf:/config/gnatsd.conf:ro,Z
    cap_drop:
      - ALL
    networks:
      signaling-backend:
        aliases:
          - nats
